In [2]:
from  scipy.spatial.distance import euclidean

p1 = (2,3)
p2 = (5,7)

print(euclidean(p1,p2))

5.0


In [6]:
def men(p1,p2):
    return abs(p2[0]-p1[0])+abs(p2[1]-p1[1])

p1 = (2,3)
p2 = (5,7)

print(men(p1,p2))

7


In [4]:
def men(x1,y1,x2,y2):
    return abs(x2-x1)+abs(y2-y1)

print(men(2,3,5,7))

7


In [8]:
 from scipy.spatial.distance import cityblock
    
p1=(2,3)
p2=(5,7)
print(cityblock(p1,p2))

7


In [13]:
from scipy.spatial import minkowski_distance
p1=(2,3)
p2=(5,7)
print(minkowski_distance(p1,p2,p=1))


7.0


In [21]:
from scipy.spatial import distance
import numpy as np
a=np.array([[0,1,1,0,0,0,1,0,0,1]])
b=np.array([[1,0,0,1,0,1,0,0,1,1]])
print(distance.cdist(a,b,'jaccard'))

[[0.875]]


In [18]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

data= pd.DataFrame([[1,2],[3,4],[5,6]])
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(data)

print(normalized_data)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


In [20]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

data= pd.DataFrame([[1,2],[3,4],[5,6]])
scaler = StandardScaler()
normalized_data = scaler.fit_transform(data)

print(normalized_data)



[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [2]:
import pandas as pd
import numpy as np

data= pd.DataFrame([[1,6,11],[2,7,np.NaN],[np.NaN,8,13],[4,np.NaN,14],[5,10,15]])
print(data.isnull())
print(data.isnull().sum())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False  False
3  False   True  False
4  False  False  False
0    1
1    1
2    1
dtype: int64


In [6]:
import numpy as np
a=np.array([2,4,7,10,100,12,15,18,22,26,30])
m=np.median(a)
a[a>3*m]=m
print(a)

[ 2  4  7 10 15 12 15 18 22 26 30]


In [10]:
import numpy as np
a=np.array([2,4,7,10,100,12,15,18,22,26,30])

q1= np.percentile(a,25)
q2=np.median(a)
q3= np.percentile(a,75)
iqr=q3-q1

bo_inf=q1-1.5*iqr
bo_sup=q3+1.5*iqr
print(bo_sup)
print(bo_inf)

a[a>bo_sup]=q2
a[a<bo_inf]=q2

print(a)


47.25
-14.75
[ 2  4  7 10 15 12 15 18 22 26 30]
